//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftDSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manager()
        {
            this.Executor = new HashSet<Executor>();
        }
    
        public int ID { get; set; }
        public int JuniorMinimum { get; set; }
        public int MiddleMinimum { get; set; }
        public int SeniorMinimum { get; set; }
        public double AnalysisCoefficient { get; set; }
        public double InstallationCoefficient { get; set; }
        public double SupportCoefficient { get; set; }
        public double TimeCoefficient { get; set; }
        public double DifficultyCoefficient { get; set; }
        public double ToMoneyCoefficient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Executor> Executor { get; set; }
        public virtual User User { get; set; }
    }
}
